### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by 0PandaDEV** [resendlabs/resend-python#44]
```
Traceback (most recent call last):
  File "/Users/pandadev/Desktop/resend test/main.py", line 4, in <module>
    resend.api_key = os.environ["re_ZsD7rmEF_4pwGvbhQi8VS51n7sxMc76mu"]
                     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 're_yourkey'
```

when i try to use the example code

```python
import os
import resend

resend.api_key = os.environ["re_yourkey"]

params = {
    "from": "email",
    "to": ["email"],
    "subject": "hi",
    "html": "<strong>hello, world!</strong>"
}

r = resend.Emails.send(params)
print(r)
```

**Comment by 0PandaDEV** [comment]
Never mind fixed it by myself, it's just `resend.api_key = "re_yourkey"`
